# Generated by Django 4.0.4 on 2023-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='explicit_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menus',
            name='named_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
