# Generated by Django 4.0.4 on 2023-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menus_explicit_url_menus_named_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='explicit_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='named_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
